SUPABASE_URL="https://hwqxyfvcnecuywfxwqdy.supabase.co"
SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3cXh5ZnZjbmVjdXl3Znh3cWR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzI0NjcsImV4cCI6MjA2MjgwODQ2N30.C0qRrrfrycnjQg1dLQM4Rzj5oG6XCg4JUhn28uYtY-E"
MASTER_KEY="cherrycherrylady"